<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>

    <parent>
        <groupId>io.github.iweidujiang</groupId>
        <artifactId>spring-cloud-alibaba-lab</artifactId>
        <version>1.0.0</version>
    </parent>

    <artifactId>07-open-feign</artifactId>
    <packaging>pom</packaging>
    <name>07 - OpenFeign</name>
    <description>OpenFeign 远程接口调用示例</description>

    <modules>
        <module>feign-provider</module>
        <module>open-feign-service</module>
    </modules>
</project>
