version: "3"
services:
  seata-server-1:
    image: seataio/seata-server:1.4.2
    hostname: seata-server
    ports:
      - "8091:8091"
    environment:
      SEATA_PORT: 8091
      SEATA_IP: ${SEATA_IP:-127.0.0.1}
      SEATA_CONFIG_NAME: file:/seata-server/resources/registry.conf
    volumes:
      - ../config/registry.conf:/seata-server/resources/registry.conf
    restart: unless-stopped
  seata-server-2:
    image: seataio/seata-server:1.4.2
    hostname: seata-server
    ports:
      - "8092:8092"
    environment:
      SEATA_PORT: 8092
      SEATA_IP: ${SEATA_IP:-127.0.0.1}
      SEATA_CONFIG_NAME: file:/seata-server/resources/registry.conf
    volumes:
      - ../config/registry.conf:/seata-server/resources/registry.conf
    restart: unless-stopped
  seata-server-3:
    image: seataio/seata-server:1.4.2
    hostname: seata-server
    ports:
      - "8093:8093"
    environment:
      SEATA_PORT: 8093
      SEATA_IP: ${SEATA_IP:-127.0.0.1}
      SEATA_CONFIG_NAME: file:/seata-server/resources/registry.conf
    volumes:
      - ../config/registry.conf:/seata-server/resources/registry.conf
    restart: unless-stopped
