# 导入 Nacos 配置中心（group: SEATA_GROUP，dataId: seataServer.properties）
# 请按实际环境修改 MySQL 连接信息

service.vgroupMapping.default_tx_group=default

store.mode=db
store.db.datasource=druid
store.db.dbType=mysql
store.db.driverClassName=com.mysql.cj.jdbc.Driver
store.db.url=jdbc:mysql://127.0.0.1:3306/seata-server?useUnicode=true&characterEncoding=utf8&connectTimeout=1000&socketTimeout=3000&autoReconnect=true&useSSL=false
store.db.user=root
store.db.password=root
