server:
  port: 7072

spring:
  application:
    name: sentinel-nacos-service
  cloud:
    nacos:
      discovery:
        server-addr: ${NACOS_SERVER:127.0.0.1:8848}
    sentinel:
      transport:
        dashboard: ${SENTINEL_DASHBOARD:localhost:8080}
        port: 8721
      web-context-unify: false
      datasource:
        flow:
          nacos:
            server-addr: ${NACOS_SERVER:127.0.0.1:8848}
            dataId: sentinelFlowRule.json
            groupId: DEFAULT_GROUP
            rule-type: flow

management:
  endpoints:
    web:
      exposure:
        include: '*'
